### ISSUE TITLE
{UPdate} Add EN Lange 

### ISSUE THREAD

**Issue by lolminerxmrig** [clebrw/Parallel-Bitcoin-Brute-Force#1]
Hi.
plz add en Lange and sample use.

**Comment by lolminerxmrig** [comment]
thanks a lot.
can best config for ( Cpu : 128 Core , RAM : 800 GIG ).

**Comment by clebrw** [comment]
In the efficiency graph made for my processor, the best option was the number of logical numbers. For your processor it would be interesting to experiment with 64 processors, I believe it is the best option. You can run ¨python3 process_BF.py 100000 128¨ and see how long you will have performance gains.

**Comment by lolminerxmrig** [comment]
Do I have a chance to win with this amount of cpu?
 My list of wallets is different.
 The link below is the wallets that I want to crack.
 Thank you for your guidance.

https://raw.githubusercontent.com/lolminerxmrig/bitcoin-bruteforce/main/wallets.txt

**Comment by lolminerxmrig** [comment]
me check list wallet balance this site:

https://www.homebitcoin.com/easybalance/

**Comment by clebrw** [comment]
Even if your hardware is powerful, it would probably take thousands of years to find one. The possibility of generating wallets is something almost as great as the number of atoms in the observable universe. At the beginning of the README I show a table comparing, let me look at it, it's very interesting.

**Comment by lolminerxmrig** [comment]
hi.
checked?

**Comment by clebrw** [comment]
Hello.
I tested it on my notebook and got 51kWallets/s with your wallets file. Even so, it would take thousands of years to find one. I suggest you leave it on for a few hours, who knows, you might be in for a surprise
